                      ##  TOD LIST COMPRAS##

# 1.TIENE QUE TENER UN MENU DONDE SE PUEDA MOSTRAR TODAS LAS OPCIONES DEL PROGRAMA
# 2.DENTRO DEL MENU TIENE QUE TENER LAS SIGUIENTES OPCIONES : CREAR LISTA DE COMPRAS , BUSCAR LISTAS ,ELIMINAR LISTAS,EDITAR LISTA,SALIR  
# 3.DENTRO DE CREAR LISTAS DE COMPRAS PRIMERO TIENE QUE CREAR EL TITULO DE LA LISTA Y UNA VEZ CREADO RECIEN PUEDE INGRESAR AL CONTENIDO 
# 4.DENTRO DE VUSCAR LISTAS VA A SALIR UN MENU QUE VA A SALIR SOLO EL TITULO DE LAS LISTAS DONDE EL USUARIO PUEDA ESCOGER CUAL ABRIR Y UNA VEZ CONFIRMADO LA LISTA QUE QUIERE VER 
# VA A PODER VER EL CONTENIDO DE LA LISTA  
# 5.Y EN ELIMINAR TAMBIEN CUANDO SELECCIONE LA OPCION VA A PODER VER SOLO EL TITULO DE LAS LISTAS CON OPCION DE PODER VER EL CONTENIDO Y TAMBIEN PODRA VOLVER AL MENU DONDE SALEN LOS TITULOS
# Y PODRA ESCOGER CUAL ELIMINAR CON UN MINIMENU QUE DIGA SI ESTA SEGURO DE ELIMINAR ESA LISTA
# 6. TAMBIEN TIENE QUE TENER UNA OPCION DE EDITAR DONDE EL USUARIO VA A PODER BUSRCAR LA LISTA POR EL NOMBRE DESPUES INGRESAR A LA LISTA Y PODRA EDITAR EL DOCUMENTO
# 7. Y POR ULTIMO LA OPCION DE SALIR QUE TERMINARA EL PROGRAMA 

# DilanRiv
